### ISSUE TITLE
Bimanual trajectory execution example not working

### ISSUE THREAD

**Issue by ghost** [fsuarez6/lenny#2]
[This example](https://github.com/fsuarez6/lenny#bimanual-trajectory-execution) doesn't work

**Comment by lakshmip001** [comment]
cat_OR_ws/src/lenny/lenny_openrave/scripts/example_bimanual_planning.py", line 8, in <module>
    from lenny_control.controllers import TrajectoryController
ImportError: No module named controllers

Is it same error that doesnt work?
